export const SET_SCREEN_SIZE = "SET_SCREEN_SIZE"
export const LOAD_SELECTED_JOBDATA = "LOAD_SELECTED_JOBDATA"
export const CLICK_JOB= "CLICK_JOB"
export const CLICK_TOGGLE= "CLICK_TOGGLE"

export const CLICK_TAB= "CLICK_TAB"


//IMPORT INTO REDUCER LATER